# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# FieldOfStudies samples
  # Uniwersytet Wrocławski
FieldOfStudy.create(name: 'Administracja', field_type: 1)
FieldOfStudy.create(name: 'Anglistyka', field_type: 9)
FieldOfStudy.create(name: 'Archeologia', field_type: 4)
FieldOfStudy.create(name: 'Astronomia', field_type: 5)
FieldOfStudy.create(name: 'Bachelor of business and administration (biznes i administracja)', field_type: 1)
FieldOfStudy.create(name: 'Bezpieczeństwo narodowe', field_type: 14)
FieldOfStudy.create(name: 'Biologia człowieka', field_type: 5)
FieldOfStudy.create(name: 'Biologia', field_type: 5)
FieldOfStudy.create(name: 'Biotechnologia', field_type: 7)
FieldOfStudy.create(name: 'Biotechnology', field_type: 7)
FieldOfStudy.create(name: 'Chemia i toksykologia sądowa', field_type: 6)
FieldOfStudy.create(name: 'Chemia medyczna', field_type: 6)
FieldOfStudy.create(name: 'Chemia', field_type: 5)
FieldOfStudy.create(name: 'Chemistry', field_type: 5)
FieldOfStudy.create(name: 'Criminal justice', field_type: 12)
FieldOfStudy.create(name: 'Dyplomacja europejska', field_type: 4)
FieldOfStudy.create(name: 'Dziedzictwo kultury materialnej – ochrona, promocja, gospodarowanie', field_type: 2)
FieldOfStudy.create(name: 'Dziennikarstwo i komunikacja społeczna', field_type: 0)
FieldOfStudy.create(name: 'Ekonomia', field_type: 10)
FieldOfStudy.create(name: 'Etnologia i antropologia kulturowa', field_type: 4)
FieldOfStudy.create(name: 'European cultures', field_type: 0)
FieldOfStudy.create(name: 'Europeistyka', field_type: 0)
FieldOfStudy.create(name: 'Filologia chorwacka z językiem serbskim', field_type: 9)
FieldOfStudy.create(name: 'Filologia czeska', field_type: 9)
FieldOfStudy.create(name: 'Filologia francuska', field_type: 9)
FieldOfStudy.create(name: 'Filologia germańska', field_type: 9)
FieldOfStudy.create(name: 'Filologia hiszpańska', field_type: 9)
FieldOfStudy.create(name: 'Filologia indyjska', field_type: 9)
FieldOfStudy.create(name: 'Filologia klasyczna', field_type: 9)
FieldOfStudy.create(name: 'Filologia polska', field_type: 9)
FieldOfStudy.create(name: 'Filologia rosyjska', field_type: 9)
FieldOfStudy.create(name: 'Filologia ukraińska', field_type: 9)
FieldOfStudy.create(name: 'Filozofia', field_type: 0)
FieldOfStudy.create(name: 'Fizyka', field_type: 5)
FieldOfStudy.create(name: 'Genetyka i biologia eksperymentalna', field_type: 6)
FieldOfStudy.create(name: 'Geografia', field_type: 5)
FieldOfStudy.create(name: 'Geologia', field_type: 5)
FieldOfStudy.create(name: 'Gospodarka przestrzenna', field_type: 1)
FieldOfStudy.create(name: 'Historia sztuki', field_type: 2)
FieldOfStudy.create(name: 'Historia', field_type: 0)
FieldOfStudy.create(name: 'Indywidualne studia informatyczno-matematyczne', field_type: 6)
FieldOfStudy.create(name: 'Indywidualne studia międzyobszarowe', field_type: 16)
FieldOfStudy.create(name: 'Informacja naukowa i bibliotekoznawstwo', field_type: 0)
FieldOfStudy.create(name: 'Informatyka', field_type: 6)
FieldOfStudy.create(name: 'Italianistyka', field_type: 9)
FieldOfStudy.create(name: 'Judaistyka', field_type: 9)
FieldOfStudy.create(name: 'Komunikacja wizerunkowa', field_type: 4)
FieldOfStudy.create(name: 'Koreanistyka', field_type: 9)
FieldOfStudy.create(name: 'Kultura i praktyka tekstu: twórcze pisanie i edytorstwo', field_type: 0)
FieldOfStudy.create(name: 'Kulturoznawstwo', field_type: 2)
FieldOfStudy.create(name: 'Matematyka', field_type: 5)
FieldOfStudy.create(name: 'Mikrobiologia', field_type: 6)
FieldOfStudy.create(name: 'Militarioznawstwo', field_type: 14)
FieldOfStudy.create(name: 'Muzykologia', field_type: 2)
FieldOfStudy.create(name: 'Niderlandystyka', field_type: 9)
FieldOfStudy.create(name: 'Ochrona środowiska', field_type: 15)
FieldOfStudy.create(name: 'Pedagogika', field_type: 11)
FieldOfStudy.create(name: 'Politologia specjalności comparative politics; global security; media and politics; europe in the world', field_type: 4)
FieldOfStudy.create(name: 'Politologia', field_type: 4)
FieldOfStudy.create(name: 'Praca socjalna', field_type: 4)
FieldOfStudy.create(name: 'Publikowanie cyfrowe i sieciowe', field_type: 0)
FieldOfStudy.create(name: 'Sinologia', field_type: 9)
FieldOfStudy.create(name: 'Socjologia ekonomiczna', field_type: 4)
FieldOfStudy.create(name: 'Socjologia grup dyspozycyjnych', field_type: 4)
FieldOfStudy.create(name: 'Socjologia', field_type: 4)
FieldOfStudy.create(name: 'Stosunki międzynarodowe specjalność global studies', field_type: 4)
FieldOfStudy.create(name: 'Stosunki międzynarodowe', field_type: 4)
FieldOfStudy.create(name: 'Studia śródziemnomorskie', field_type: 16)
FieldOfStudy.create(name: 'Turystyka', field_type: 8)
FieldOfStudy.create(name: 'Zarządzanie migracjami', field_type: 1)
FieldOfStudy.create(name: 'Zarządzanie projektami społecznymi', field_type: 1)
FieldOfStudy.create(name: 'Zarządzanie środowiskiem przyrodniczym', field_type: 1)

# HighSchool samples
HighSchool.create(name: 'II Liceum Ogólnokształcące im. Hugona Kołłątaja w Wałbrzychu', city: 'Wałbrzych', school_type: 0)
HighSchool.create(name: 'XVI Liceum Ogólnokształcące im. Stefana Batorego w Białymstoku', city: 'Białystok', school_type: 0)
HighSchool.create(name: 'Technikum Komputerowe w Świdnicy', city: 'Świdnica', school_type: 1)
HighSchool.create(name: 'Technikum Energetyczne w Wałbrzychu', city: 'Wałbrzych', school_type: 1)
HighSchool.create(name: 'I Liceum Ogólnokształcące im. Józefa Piłsudskiego w Krotoszynie', city: 'Krotoszyn', school_type: 0)

# Academy samples
Academy.create(name: 'Uniwersytet Wrocławski', city: 'Wrocław', academy_type: 0)
Academy.create(name: 'Politechnika Opolska', city: 'Opole', academy_type: 1)
Academy.create(name: 'Akademia Sztuk Pięknych', city: 'Wrocław', academy_type: 4)
Academy.create(name: 'Uniwersytet Medyczny w Łodzi', city: 'Łódź', academy_type: 3)
Academy.create(name: 'Uniwersytet Przyrodniczy w Lublinie', city: 'Lublin', academy_type: 5)

# MaturaSubject samples
MaturaSubject.create(name: 'Biologia', subject_type: 1)
MaturaSubject.create(name: 'Chemia', subject_type: 1)
MaturaSubject.create(name: 'Filozofia', subject_type: 0)
MaturaSubject.create(name: 'Fizyka', subject_type: 1)
MaturaSubject.create(name: 'Geografia', subject_type: 1)
MaturaSubject.create(name: 'Historia', subject_type: 0)
MaturaSubject.create(name: 'Historia muzyki', subject_type: 0)
MaturaSubject.create(name: 'Historia sztuki', subject_type: 0)
MaturaSubject.create(name: 'Informatyka', subject_type: 1)
MaturaSubject.create(name: 'Język łaciński i kultura antyczna', subject_type: 0)
MaturaSubject.create(name: 'Język mniejszości etnicznej', subject_type: 0)
MaturaSubject.create(name: 'Język mniejszości narodowej', subject_type: 0)
MaturaSubject.create(name: 'Język regionalny', subject_type: 0)
MaturaSubject.create(name: 'Matematyka', subject_type: 1)
MaturaSubject.create(name: 'Język polski', subject_type: 0)
MaturaSubject.create(name: 'Wiedza o społeczeństwie', subject_type: 0)
MaturaSubject.create(name: 'Język angielski', subject_type: 0)
MaturaSubject.create(name: 'Język francuski', subject_type: 0)
MaturaSubject.create(name: 'Język hiszpański', subject_type: 0)
MaturaSubject.create(name: 'Język rosyjski', subject_type: 0)
MaturaSubject.create(name: 'Język włoski', subject_type: 0)

# FieldDetail samples
  # Uniwersytet Wrocławski